### ISSUE TITLE
Linking images in categories

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#1]
Hi @tomswain84, all images on categories should link to the product page:

![image](https://user-images.githubusercontent.com/14006273/167407486-d38c9bcc-8e4f-409a-b712-87a7a7f82fbe.png)

**Comment by josephcotten** [comment]
@daviddubrino was this fixed?

**Comment by josephcotten** [comment]
Just tested and confirmed as fixed on the Next.js/Vercel site.
