### ISSUE TITLE
WIP - Creating a List: 

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#10]
## Design tweaks and Site Fixes

- [ ] Homepage: Make this entire section clickable with a link to the product (this is prime real estate for running our promotions):
![image](https://user-images.githubusercontent.com/14006273/174677313-c60a5738-c5df-4304-a6f2-7525250352f9.png)

- [ ] Homepage: This should overlap at a larger viewable area by design as now it shows a lot of black space:
![image](https://user-images.githubusercontent.com/14006273/174676548-d1bc36ca-83b2-44d8-b1f3-5e01257626a4.png)

It only overlaps at this width: 
![image](https://user-images.githubusercontent.com/14006273/174676606-3c1f195a-3996-4ff0-b12c-66d2fe783c90.png)

- [ ] Homepage Switching out this D with something else:
![image](https://user-images.githubusercontent.com/14006273/174676676-657cc171-d3d3-4684-9229-f8a4945ab42b.png)

- [ ] Homepage: Populating customer reviews with real reviews, either pulled dynamically from hand-picked reviews:
![image](https://user-images.githubusercontent.com/14006273/174676808-bbb8cc8b-a6c5-4f51-a9c5-b337122f1760.png)

- [ ] Footer: This link should open the following link in the same window: https://www.daskeyboard.com/blog/mechanical-keyboard-guide/

![image](https://user-images.githubusercontent.com/14006273/174676940-7e8ca025-4c8c-4098-b35a-b599a0eac73d.png)

# MIssing Pages: 

- https://dascommerce.vercel.app/technology/q-software
- https://dascommerce.vercel.app/technology/gamma-zulu-switch

### Prior to Launch

- [ ] Giveaway page: To update giveaway script prior to launch: https://dascommerce.vercel.app/giveaway
Since this will likely be in July, here is that code:
```
<a class="e-widget no-button generic-loader" href="https://gleam.io/sMrvH/july-2022-das-keyboard-monthly-giveaway" rel="nofollow">July 2022 Das Keyboard Monthly Giveaway</a>
<script type="text/javascript" src="https://widget.gleamjs.io/e.js" async="true"></script>
```

**Comment by josephcotten** [comment]
@daviddubrino are we safe to begin working on these Issues? We haven’t yet because of the WIP in the title.

**Comment by daviddubrino** [comment]
Closed and created separate issues!
