### ISSUE TITLE
Frequently Bought Together

### ISSUE THREAD

**Issue by josephcotten** [tomswain84/daskeyboardsite#11]
@daviddubrino and @mrth2 I want to start a fresh Git Issue on this because I’m confused as to what needs to be done.

This is in regards to the Frequently Bought Together widget which appears on product commerce pages.

@mrth2 you said you’ll need to query the Shopify API to pull that product info onto the product page. Is there anything else you need from us? David gave me a screenshot of the Shopify App he uses to create those bundles, which I am attaching to this ticket. Does this help?

![unnamed](https://user-images.githubusercontent.com/9754619/176027415-63bf7e9f-f291-4ca3-a6c6-5ad35015c071.png)

**Comment by mrth2** [comment]
@josephcotten  @daviddubrino  I extracted data from codeblackbelt app public API to load the bundle here ( apply to all similar purchase pages )
https://dascommerce.vercel.app/products/commerce/5qs

**Comment by daviddubrino** [comment]
Perfect, it has the correct products, and the bundle is added to the cart as expected.
