### ISSUE TITLE
Pre-Launch SEO

### ISSUE THREAD

**Issue by josephcotten** [tomswain84/daskeyboardsite#12]
I am starting a new Git Issue ticket to specifically address the **pre-launch** SEO work which we need to complete.

1. Meta Descriptions: @daviddubrino I don’t have these on file; do you?
2. Meta Title Tags: @mrth2 I believe NextJS automatically creates title tags, correct? Has anyone verified that they match the page titles on the live site (daskeyboard.com)?
3. Opengraph images for social media sharing ( og:image tag ) — I would assume the og:image for each page should be either be the product image for product pages, or the logo for non-product pages. @daviddubrino does that sound right to you? @mrth2 does NextJS have a module to add opengraph data to pages?
4. Scheme.org markup on all pages, but especially product pages. @mrth2 does NextJS have a module to add in schema classifications during the building process? I just did a quick search on this and found this: https://www.loudnoises.us/adding-schema-data-to-next-js-sites/
5. Product Reviews for Google Searches. @mrth2 can we add this? https://developers.google.com/search/docs/advanced/structured-data/review-snippet

**Comment by mrth2** [comment]
@josephcotten  I did copy page titles from daskeyboard.com.

Do we need to copy all current SEO from original site to NextJS version?  ( description, open graph, schema, review snippet, etc )

**Comment by josephcotten** [comment]
@daviddubrino I believe your current/original site is missing opengraph and schema.org markup, correct? What **can** we copy over from the original site from that list?

**Comment by daviddubrino** [comment]
Yes, the existing site is missing or has incomplete opengraph and schema markup - I can start to work on the details for the pages, but can it be done inside Vercel so there's not double the work?  @josephcotten @mrth2

**Comment by mrth2** [comment]
@daviddubrino  @josephcotten  the schema markup & SEO have been updated:
eg: https://validator.schema.org/#url=https%3A%2F%2Fdascommerce.vercel.app%2Fmodel-s-pro-for-mac

**Comment by josephcotten** [comment]
Just confirming here the Schema.org markup is in place. With the link given above, if we compare that to the old site ( https://validator.schema.org/#url=https%3A%2F%2Fwww.daskeyboard.com%2Fmodel-s-professional-for-mac%2F ) you can see there’s no markup on the old site, but we’ve added it on the new site.
