### ISSUE TITLE
Next Milestones

### ISSUE THREAD

**Issue by josephcotten** [tomswain84/daskeyboardsite#14]
Next milestones:
- We need a purchase page to list the keyboard variant with ATC form, the best-selling products, and frequently bought together bundle.
- We also need to create eight missing pages:
	+ the refurbished product list needs API integration
	+ keyboard comparison page needs custom code, I asked Natalie if she can have the code from client, if there's no React version, I will create it myself.
	+ others are static pages with template instructions.
- Resolve remaining open Git Issues tickets.

@daviddubrino this is an update from us on our next milestones.
@mrth2 is there anything else you need from us to tackle these?

**Comment by mrth2** [comment]
@josephcotten all of those tasks have been resolved
