### ISSUE TITLE
Compare Keyboards Code - Fixed?

### ISSUE THREAD

**Issue by josephcotten** [tomswain84/daskeyboardsite#15]
@daviddubrino and @mrth2 I’m following up on an old issue, just to make sure we have resolved it.

David, you posted a Git issue a while back with this:
Compare Keyboards: https://dascommerce.vercel.app/compare-keyboards should be: https://www.daskeyboard.com/compare-keyboards/ - I believe you have the code for this already.

You can just use the basic static page theme: https://www.4eighty.com/sites/daskeyboard/company-information/become-a-reseller.php

———
**I don’t think we have the code for that table.** @mrth2 am I wrong? Do you have that code?

**Comment by mrth2** [comment]
@josephcotten  @daviddubrino  I created one myself here: https://dascommerce.vercel.app/compare-keyboards

**Comment by daviddubrino** [comment]
Thank you, the widget is working correctly, it just needs the padding on the table, and then the results under the keyboards to be center-aligned such as: https://www.daskeyboard.com/compare-keyboards/#!?keyboard1=1

![image](https://user-images.githubusercontent.com/14006273/176175156-89608803-823b-40a6-8d41-3bc2c1812585.png)

**Comment by mrth2** [comment]
@daviddubrino styling updated
