### ISSUE TITLE
Q Series Line up block on Software and Gamma Zulu Switches pages

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#17]
The Q Series Lineup Block at the bottom of the page should be the same as it is on the keyboards. Example: https://dascommerce.vercel.app/products/daskeyboard/5qs

![image](https://user-images.githubusercontent.com/14006273/176257987-ec9cff43-c801-427c-80b8-ccda524f5460.png)

On the Gamma Zulu Switch page, it's only showing two: https://dascommerce.vercel.app/technology/gamma-zulu-switch
![image](https://user-images.githubusercontent.com/14006273/176258159-fe8ac8b4-1827-4164-be07-2dfc53e60dc8.png)

On the Q Software page it's not spaced correctly (center aligned): https://dascommerce.vercel.app/technology/q-software
![image](https://user-images.githubusercontent.com/14006273/176258264-b5e29c82-cb08-4247-85d8-89f6b3d5d2ea.png)

**Comment by mrth2** [comment]
@daviddubrino related products styling has been aligned. 

FYI, the Gamma Zulu Switch page has only two products because the third one is `Cherry MX`, not `Gamma zulu`. Let me know if we still need to show `4Q` keyboard there

**Comment by daviddubrino** [comment]
This page is still missing the 4Q: https://dascommerce.vercel.app/technology/gamma-zulu-switch
