### ISSUE TITLE
Refurbished top nav link to new Category Page

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#18]
The top nav needs to have the link changed to the refurbished page: https://dascommerce.vercel.app/products/category/refurbished-mechanical-keyboards

**Comment by mrth2** [comment]
@daviddubrino refurbished nav links fixed

**Comment by daviddubrino** [comment]
For me it is still going to: https://dascommerce.vercel.app/products/category/mechanical-keyboards?filter=refurbished

![image](https://user-images.githubusercontent.com/14006273/176431889-a66ab321-ad2c-4f6d-bd09-6814ae0abca0.png)

**Comment by mrth2** [comment]
@daviddubrino menu link fixed
