### ISSUE TITLE
Refurbished disclaimer edit

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#19]
Then can you make the disclaimer just like the one on the shop product page here: https://shop.daskeyboard.com/collections/refurbished-mechanical-keyboards/products/refurbished-das-keyboard-4-professional?variant=796097009
![image](https://user-images.githubusercontent.com/14006273/176258967-6d0743db-3f21-4841-8d7a-1b348db7f3d3.png)

Instead of: 
![image](https://user-images.githubusercontent.com/14006273/176259064-e3c645cb-f48b-42be-9d06-73e754ee0888.png)

**Comment by mrth2** [comment]
@daviddubrino disclaimer style matched with the store, anw, font are using Roboto and can not be bold as the store. Please reopen this issue if needed
