### ISSUE TITLE
Adding Refurbished Disclaimer to Product checkout pages

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#20]
We will also need this disclaimer on the product checkout pages for each refurbished model: 
![image](https://user-images.githubusercontent.com/14006273/176260395-824fef80-303f-45eb-aca6-c24c26e65ca3.png)

- https://dascommerce.vercel.app/products/commerce/refurbished-x50q
- https://dascommerce.vercel.app/products/commerce/refurbished-5qs
- https://dascommerce.vercel.app/products/commerce/refurbished-4q
- https://dascommerce.vercel.app/products/commerce/refurbished-4-ultimate
- https://dascommerce.vercel.app/products/commerce/refurbished-4-professional-for-mac
- https://dascommerce.vercel.app/products/commerce/refurbished-4c-tkl
- https://dascommerce.vercel.app/products/commerce/refurbished-prime-13
- https://dascommerce.vercel.app/products/commerce/refurbished-model-s-pro
- https://dascommerce.vercel.app/products/commerce/refurbished-model-s-pro-for-mac

**Comment by mrth2** [comment]
@daviddubrino disclaimer added to product pages
