### ISSUE TITLE
Centering content on Meta Hacks page

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#21]
We should center the content on the meta hacks page here: https://dascommerce.vercel.app/5-meta-hacks

So it resembles the existing: 
![image](https://user-images.githubusercontent.com/14006273/176272807-27712fb5-a068-43e2-b140-a7ffb6b16ee2.png)

**Comment by mrth2** [comment]
@daviddubrino this page has been updated
