### ISSUE TITLE
New D graphic added to homepage

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#22]
Getting examples from Daniel on Friday then create or find a good graphic to replace this one
![image](https://user-images.githubusercontent.com/14006273/176273175-6fbc54be-d52c-4b6d-90d2-13305a6235ef.png)

**Comment by josephcotten** [comment]
@daviddubrino @supercobra I created two new design ideas for this “D” typography glyph. Take a look: https://miro.com/app/board/uXjVOX2cK9w=/?moveToWidget=3458764528574421122&cot=14

Thoughts?

**Comment by mrth2** [comment]
@josephcotten D graphic updated
