### ISSUE TITLE
Homepage region clickable to product

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#23]
Can we make this entire section clickable with a link to the product (this is prime real estate for running our promotions): https://dascommerce.vercel.app/products/daskeyboard/4-ultimate

![image](https://user-images.githubusercontent.com/14006273/176273601-890616f1-7e6c-4a9a-adff-c649b2951d0f.png)

**Comment by mrth2** [comment]
@daviddubrino home hero banner now is link to 4 ultimate product
