### ISSUE TITLE
Customer reviews on homepage updated

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#24]
Populating customer reviews with real reviews, either pulled dynamically from hand-picked reviews:

![image](https://user-images.githubusercontent.com/14006273/176273848-47b6af6c-84d0-4f02-a479-28deedc2c0fa.png)

Hand-picked reviews: 

**My 3rd Das Keyboard.** I love these keyboards. My oldest one that's 8 years old still works like it did on day 1. I would never buy all these "gamer" keyboards before a Das. Works great for work and gaming.
John T.
Jun 01, 2022
ON THE DAS KEYBOARD X50Q

**Clicky and amazing.** Everyone in my office hates me. But I don't care. I love it.
Timothy M.
Jun 01, 2022
ON THE DAS KEYBOARD 4 PROFESSIONAL FOR MAC

**Best keyboard available.** if you want the best feel and touch of a real keyboard this is the best one I've found. The addition USB ports are helpful but the touch and feel of these keyboards is second to none. I bought them for the office and home.
Emmett B.
Jun 01, 2022
ON THE DAS KEYBOARD 4 PROFESSIONAL

**Great quality.**  Absolutely worth the money. It improved my typing speed, accuracy, and enjoyment.
Josiah P.
Jun 01, 2022
ON THE DAS KEYBOARD 4 ROOT

**Superior Product**. I love the touch of this quality switching keyboard.
William L. 
Jun 01, 2022
ON THE DAS KEYBOARD MODEL S

**Really love it.** I have used an incredibly wide asst of keyboards and this is amongst the best. The feel of typing on it is so satisfying and seems to be extremely well built. I have been using it about 6 weeks and is perfect so far.
Jonathan O.
May 03, 2022
ON THE DAS KEYBOARD X50Q

**Love the feel.** I really like the aluminum plate, the keys feel great, and it looks great on my desk! 
Scott F.
May 03, 2022
ON THE DAS KEYBOARD 4C TKL

**Better than Apple, less money.** We have two of these in our family and we find them to be more responsive and reliable than Apple’s keyboards and they cost less. 
Jim P.
Apr 02, 2022
ON THE DAS KEYBOARD MODEL S FOR MAC

**My wife loves it!** This was our first mechanical keyboard. I got it for my wife for her work-from-home PC. She loves it!
Steven K.
Feb 03, 2022
ON THE DAS KEYBOARD 4Q

**Exceptional all these years.** Been using Ultimates at home and work since I first saw them on The Awesomer back in late 2008. Absolutely wonderful keyboards with zero issues out of the box, wonderful performance and lifespan.
Brendan O.

Feb 02, 2022
ON THE DAS KEYBOARD ULTIMATE

**Nothing Beats a Das Keyboard.** I have a Model S Professional that is about 10 years old now which has become my work keyboard. I needed a new keyboard for my home PC and tried a couple of different brands out but none of them had the same build quality or level of reliability that I had come to expect. Das boards are by far the most durable I've ever used and will likely be the only brand I buy moving forward
Bill K.
Jan 03, 2022
ON THE DAS KEYBOARD 5QS

**Comment by mrth2** [comment]
@daviddubrino customer reviews list updated using hand picked reviews:
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/8658653/176351151-5471a2a8-c477-4eae-8d0c-830b2838a453.png">
