### ISSUE TITLE
Commerce pages all have STARTING AT$199 needs space between AT $199

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#26]
On the product commerce pages there is no space between AT$PRICE: https://dascommerce.vercel.app/products/commerce/5qs
https://dascommerce.vercel.app/products/commerce/model-s-pro-for-mac
https://dascommerce.vercel.app/products/commerce/x50q
https://dascommerce.vercel.app/products/commerce/4q
https://dascommerce.vercel.app/products/commerce/4-professional
https://dascommerce.vercel.app/products/commerce/4-ultimate
https://dascommerce.vercel.app/products/commerce/4-professional-for-mac
https://dascommerce.vercel.app/products/commerce/prime-13
https://dascommerce.vercel.app/products/commerce/model-s-pro

![image](https://user-images.githubusercontent.com/14006273/176454812-40b632f6-5308-443b-8095-93e51aeea3fa.png)

**Comment by mrth2** [comment]
@daviddubrino starting price padding fixed
