### ISSUE TITLE
Klarna Popup does not work on product commerce pages

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#28]
Let me know if you need me to get the code from Klarna or if you can fix this without: 

![image](https://user-images.githubusercontent.com/14006273/176464327-42189037-8db4-4977-a46e-f5a104f3a705.png)

Should pop this message: 
![image](https://user-images.githubusercontent.com/14006273/176464173-bd99b658-9d5a-411e-bd4f-357deaa42669.png)

**Comment by mrth2** [comment]
@daviddubrino  klarna popup fixed https://dascommerce.vercel.app/products/commerce/x50q
