### ISSUE TITLE
Refurbished product commerce pages not showing correct price in Order Total

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#29]
The order total price is the new, not the refurbished price on the product commerce pages when they don't have a variant:
https://dascommerce.vercel.app/products/commerce/refurbished-x50q
https://dascommerce.vercel.app/products/commerce/refurbished-5qs
https://dascommerce.vercel.app/products/commerce/refurbished-4q
https://dascommerce.vercel.app/products/commerce/refurbished-4-professional
https://dascommerce.vercel.app/products/commerce/refurbished-4-professional-for-mac
https://dascommerce.vercel.app/products/commerce/refurbished-4c-tkl

![image](https://user-images.githubusercontent.com/14006273/176464650-5a71e11b-10a8-4731-8316-d468b379ec26.png)

**Comment by mrth2** [comment]
@daviddubrino  price fixed
