### ISSUE TITLE
CCPA Shopify App Information

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#3]
I was able to track this link actually being generated by a Shopify app, to remove the personal information from Shopify.

The link only displays on this page when you are browsing from California: https://shop.daskeyboard.com/pages/ccpa-opt-out

### Example of it working when in California:
<img width="1757" alt="Screen Shot 2022-05-24 at 4 31 55 PM" src="https://user-images.githubusercontent.com/14006273/170127799-2d4aff5a-1fd3-467a-8f14-fb14e2f8df31.png">
<img width="1833" alt="Screen Shot 2022-05-24 at 4 32 07 PM" src="https://user-images.githubusercontent.com/14006273/170127818-63d7630c-6259-4454-b54a-7a25e5d148d3.png">

### App information:
![image](https://user-images.githubusercontent.com/14006273/170127751-82363cce-746a-417f-bffb-f1ba2ebd9586.png)

![image](https://user-images.githubusercontent.com/14006273/170127938-00f4df1f-22f3-45ba-b37d-2e8fff3b931b.png)

**Comment by josephcotten** [comment]
Is this page working as expected on the Vercel site? https://dascommerce.vercel.app/ccpa-opt-out

**Comment by daviddubrino** [comment]
Unfortunately, no. When I turn my VPN on from inside of California the link does not appear the way it does on Shopify, worst case we can still host this page on Shopify and re-theme that page in Liquid as well:
<img width="1010" alt="Screen Shot 2022-06-27 at 10 39 50 AM" src="https://user-images.githubusercontent.com/14006273/175967841-50c9ca00-5863-49f3-a302-b0531640c8f3.png">
<img width="1103" alt="Screen Shot 2022-06-27 at 10 39 42 AM" src="https://user-images.githubusercontent.com/14006273/175967843-6c1e44bf-c8a2-42e0-af5c-fd4a66ec647d.png">

**Comment by mrth2** [comment]
@daviddubrino  I attached the script from shopify store ccpa page here:
https://dascommerce-git-fixccpa-tomswain84.vercel.app/ccpa-opt-out

anw, I don't have california vpn to test so can you test if it works

**Comment by daviddubrino** [comment]
Sorry, it's still not working, but is on the shopify page @mrth2: 
![Screen Shot 2022-06-28 at 7 56 24 AM](https://user-images.githubusercontent.com/14006273/176172606-33c43a98-eb67-47d6-9081-14e7ebd1f578.png)

**Comment by josephcotten** [comment]
On today’s call, we decided it might be best to simply link over to the Shopify-hosted page for this and for GDPR issues. So instead of building our own page and troubleshooting the script, @mrth2 let’s just point this link over to the Shopify-hosted page(https://shop.daskeyboard.com/pages/ccpa-opt-out)

**Comment by mrth2** [comment]
@josephcotten  link updated on footer
