### ISSUE TITLE
All product commerce page images are blurry and low res

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#30]
The images being pulled into the product commerce pages are low res, unlike what they are on Shopify: 

- On Vercel: https://dascommerce.vercel.app/images/product-images/cards/img-daskeyboard-4-professional.jpeg
- Shopify's Lead image we should try to use: https://cdn.shopify.com/s/files/1/0152/0433/products/DK4PRO-CornerBrown.png?v=1559632880
  - Expanded view of: https://shop.daskeyboard.com/collections/best-sellers/products/das-keyboard-4-professional?variant=594246125

**Comment by mrth2** [comment]
@daviddubrino commerce page now using original product images from shopify store
