### ISSUE TITLE
Where do you think we should put the Compare button/link?

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#31]
With the new design, we don't include the compare button anywhere, and this is a great tool, where do you think we should include it? 

Here are some thoughts, but I'll leave it up to you two! 
![compare](https://user-images.githubusercontent.com/14006273/176496956-cd6cac08-aee5-468d-9db6-573fb91e6397.png)

![image](https://user-images.githubusercontent.com/14006273/176497132-92281210-b1a2-4c7c-b1b5-348829d5b6b7.png)

**Comment by mrth2** [comment]
@daviddubrino I vote for adding the link to menu dropdown

**Comment by daviddubrino** [comment]
@supercobra can you choose for us? I could go either way

**Comment by daviddubrino** [comment]
Closing because this is in the dropdown menu already
