### ISSUE TITLE
Compare page tweaks

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#33]
On the compare page, there are a few fixes: https://dascommerce.vercel.app/compare-keyboards

- [x] The images are stretched and not maintaining their aspect ratio.
- [x] Capitalize the D on the X50Q
![image](https://user-images.githubusercontent.com/14006273/176436381-7a5d83c3-2d84-47b8-8468-c64c0de419d6.png)
- [x] On the these models can you please make the switch lifecycle 100 million?
  - 4 Professional
  - Model S
  - Prime 13
  - 4Q

**Comment by mrth2** [comment]
@daviddubrino compare page fixed
