### ISSUE TITLE
Copyright and icons at bottom of site

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#36]
The copyright statement should read:
Hello from Austin
© 2005-2022 - All rights reserved. Das Keyboard is a registered trademark and copyright of Metadot.

Right now there is no ©, the dates are reversed, and there's no space between the first and second sentence, and the blog icon is not linked. 

![image](https://user-images.githubusercontent.com/14006273/176502748-4ff9bd88-1772-4131-9efc-c2a7cfb911cd.png)

**Comment by mrth2** [comment]
@daviddubrino copyright text fixed & blog linked
