### ISSUE TITLE
Shop by category /products page missing

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#37]
I believe this button is supposed to go here: https://www.4eighty.com/sites/daskeyboard/products/

![image](https://user-images.githubusercontent.com/14006273/176504099-8ef308d0-3ff0-46dc-8a39-19e515bb64c6.png)

![image](https://user-images.githubusercontent.com/14006273/176504215-2c857ac0-d0a5-4d10-9447-7b23eda9dd8d.png)

**Comment by mrth2** [comment]
@daviddubrino updated /products page
