### ISSUE TITLE
All accessories product pages will need to be made in a basic format

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#40]
**For all of the products in the Accessories category**, we'll need just a basic product page (not a full commerce/product details page), and they can be linked directly to the cart, if that’s easier. For design of that simple product page template, we can use a simple page like: https://dascommerce.vercel.app/products/daskeyboard/model-s-pro-for-mac 

The Accessories Category is at:
https://dascommerce.vercel.app/products/category/accessories

**Products that do not need to be created:** 
- https://dascommerce.vercel.app/products/commerce/accessories/artisan-keycap-das-keyboard-limited-edition-escape-key
- https://dascommerce.vercel.app/products/commerce/accessories/das-keyboard-triangle-mouse-pad

The mousepads section can be removed/replaced.

**Comment by josephcotten** [comment]
@mrth2 does that sound good? Or have you already made full product details pages/commerce pages for the products in the Accessories category? I like David’s idea of using a simpler layout for the Accessories category products.

**Comment by mrth2** [comment]
@josephcotten I don't find enough content or images to make the accessory product pages. Can we just direct accessory product to the original store, same as on www.daskeyboard.com?

https://shop.daskeyboard.com/collections/accessories/products/das-keyboard-professional-keycap-set?variant=37287450116

**Comment by daviddubrino** [comment]
@mrth2 we just want to have a commerce page pulling from what's on Shopify into Vercel for accessories:
![image](https://user-images.githubusercontent.com/14006273/184140796-6914a26a-077c-479a-9205-bd726a5bfcea.png)

**Comment by josephcotten** [comment]
@daviddubrino @supercobra during our last call, we talked through this. The original plan was to have the Accessory products’ “Buy Now” button send the user straight to that product’s Shopify commerce page. I do recall us discussing, in an earlier meeting, designing a simple product details template, but my understanding was we would keep the old site’s functionality for launch. So the UX flow would be this:

1. User navigates to Accessories category listing page: https://dascommerce.vercel.app/category/accessories
2. User clicks on the “Buy Now” button for an accessory, and is taken to that page’s Shopify page (if they click the Gray PBT keycap set, they would go here: https://shop.daskeyboard.com/collections/accessories/products/pbt-keycap-set-104-key-gray?variant=32335083864147 )
3. They can then add to cart or continue shopping.

On our last call, the plan I stated was that I would map out links for @mrth2 to implement, to send each Accessory Buy Now button to the correct Shopify details page. **Is that a good plan for us?**

**Comment by josephcotten** [comment]
@mrth2 there’s a fix needed here. See my comment above for the desired functionality. Currently, when a user is on the Accessories category page ( https://dascommerce.vercel.app/category/accessories ), and they click on “Buy Now”, the aren’t sent to the Shopify product page. Instead they are taken to an unnecessary page with another Buy Now link. Instead, we want users to go straight to the product’s Shopify page when they click on it from the Accessories page.

**Comment by josephcotten** [comment]
@mrth2 here’s an explainer video: https://www.loom.com/share/757fa5b76d194a0a8584126a0bf18c90

**Comment by mrth2** [comment]
@josephcotten  the accessories are now link to shopify product page when you click on buy now

**Comment by josephcotten** [comment]
@supercobra @daviddubrino this is fixed now. Here’s a video demonstration: https://www.loom.com/share/a2cca6741ca848d3999c4fa2e8f68e5e

**Comment by josephcotten** [comment]
Reopening this because I misunderstood the assignment. We need to design a commerce page template for the Accessories pages.
