### ISSUE TITLE
Homepage needs Learn more button for Q software

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#42]
We will need this learn more button, linking to /technology/q-software/
![image](https://user-images.githubusercontent.com/14006273/176510882-19453f93-a5b6-457e-8fd5-2955e2a89461.png)

Here: 
![image](https://user-images.githubusercontent.com/14006273/176510757-3fdeed73-9b47-4a75-bdef-2a8851a7d4e2.png)

**Comment by mrth2** [comment]
@daviddubrino  button linked
