### ISSUE TITLE
Switch comparison page

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#43]
We are missing the switch comparison page on the vercel site: https://www.daskeyboard.com/switches/#!?switch1=1&switch2=2

Then once we have this we can link here on the homepage: 
![image](https://user-images.githubusercontent.com/14006273/176510998-ad6524f6-0c08-4cd3-8ee7-315d60e4506e.png)

And in the footer: 
![image](https://user-images.githubusercontent.com/14006273/176512441-f16d6ab6-94fb-416b-bdce-c3db8d1cad60.png)

**Comment by mrth2** [comment]
@daviddubrino switch page added & links updated
