### ISSUE TITLE
Cleaning up url structure for products? 

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#44]
Typically I would never change the URLs and structure when launching a new site, so that we don't have to redirect all the links and potentially lose page rank, but these don't follow any structure and might be complicated to maintain or set the way we want so asking what you two think? 

  - /x/x50q-rgb-mechanical-keyboard/
  - /p/5qs-smart-rgb-mechanical-keyboard/
  - /p/4q-smart-rgb-mechanical-keyboard/
  - /daskeyboard-4-professional/
  - /daskeyboard-4-ultimate/
  - /daskeyboard-4-professional-for-mac/
  - /daskeyboard-4C-tkl/
  - /p/prime13-mechanical-keyboard/
  - /model-s-professional/
  - /model-s-professional-for-mac/

Currently on vercel we are using this structure: 

- /products/daskeyboard/x50q
- /products/daskeyboard/commerce/x50q
- /products/category/mechanical-keyboards?filter=smartrgb

It might be best to use a uniform structure such as the below, but we will take an initial SEO hit:
- /model-s-professional 
- /commerce/model-s-professional 
- /category/mechanical-keyboards
- /category/accessories

But I'll let you two discuss and make the decision!

**Comment by mrth2** [comment]
@daviddubrino  @josephcotten  it's not an issue. I can update the URL structure like you mentioned. Please confirm if we go with it

**Comment by supercobra** [comment]
@mrth2 @josephcotten let's keep URL as requested by @daviddubrino.

**Comment by josephcotten** [comment]
Ok, so @mrth2 we are confirmed to use a URL structure that looks like this:

/model-s-professional
/commerce/model-s-professional
/category/mechanical-keyboards
/category/accessories

**Comment by josephcotten** [comment]
@daviddubrino we don’t yet have a product page for the new MacTigr product. We should get images and info from you for that so it can be ready for launch, since that product is launching soon, right? Or it just launched?

**Comment by daviddubrino** [comment]
Hi @josephcotten, yes, it is launching Tuesday. I will upload everything once they're 100% final. I have to edit one image today and then they should be good to go.

**Comment by josephcotten** [comment]
Perfect!

**Comment by josephcotten** [comment]
Yes, @mrth2 we should do a new Issue for the new MacTigr page. I‘ll take care of creating that Issue.
