### ISSUE TITLE
Source code access for daskeyboard.com

### ISSUE THREAD

**Issue by mrth2** [tomswain84/daskeyboardsite#46]
@daviddubrino  I would like to access to original site daskeyboard.com source code & the CMS behind ( if any ) so it will be much easier & quickier to migrate SEO settings instead of copying from the website.

**Comment by daviddubrino** [comment]
This would have to be done by @supercobra so will assign it to him while I'm on vacation.

**Comment by mrth2** [comment]
@supercobra  please give me access to source code on daskeyboard.com

**Comment by josephcotten** [comment]
@supercobra @daviddubrino just following up on this, as it’s a pretty important part of us reaching our milestones. We’d rather not copy the SEO elements and translation data page-by-page manually, as it will cause issues and gaps in coverage. If we can get original size source code to @mrth2 that will ensure we don’t miss anything.

What can I do to assist with this?

**Comment by supercobra** [comment]
Added @mrth2 to https://github.com/metadot/www.daskeyboard.com
