### ISSUE TITLE
Linking product name to #top on product pages

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#47]
On our existing site we link the name of the product to the #top, which I just discovered today and is another good solution for back to top (in addition to #8): 

![image](https://user-images.githubusercontent.com/14006273/176710185-fae85d64-61e8-4d1c-abbd-b33534a6b391.png)

**Comment by mrth2** [comment]
@daviddubrino product title are not scroll to top like the bottom right button
