### ISSUE TITLE
Future items or prior to launch items? 

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#48]
I've found a few things that were overlooked in the design phase, so we should decide if we roll these into the next phase, or if they're necessary for launch

Feel free to check the ones you think are essential for launch and I can create tickets for them:
- [x] There is not an image carousel on the homepage (I'm personally ok with this based on the old [https://shouldiuseacarousel.com/](https://shouldiuseacarousel.com/))
- [x] There are no image carousels on the product pages
- [x] Asteroid game implementation
- [ ] Wishlist integration (#39 )
- [x] Login to account integration (#39 )
- [x] Product commerce pages for accessories #40)
- [x] Applet pages 
![image](https://user-images.githubusercontent.com/14006273/176507297-54dbf4e0-74ef-479a-8f44-64efc299ed23.png)

**Comment by josephcotten** [comment]
@daviddubrino @supercobra for what it’s worth, I think we’d all get a big encouragement from launching the site sooner rather than later. Therefore, I’d suggest we keep all new work for Phase 2, even if Phase 2 happens a week after the launch of Phase 1.

**Comment by josephcotten** [comment]
@supercobra can you check the items in David’s original ticket above which you feel are crucial to have in place before the launch?

**Comment by supercobra** [comment]
@josephcotten nice carousel implementation here: https://www.logitech.com/

**Comment by josephcotten** [comment]
@mrth2 here’s a detail of the Photoshop mockup:
![carousel-detail](https://user-images.githubusercontent.com/9754619/184362445-4c33b622-c759-44ac-a4cc-9f53094da505.jpg)

**Comment by josephcotten** [comment]
Here’s a link to the mockups on the Miro board: https://miro.com/app/board/uXjVOX2cK9w=/?moveToWidget=3458764531173100518&cot=14

**Comment by mrth2** [comment]
@josephcotten  the product gallery carousel & Asteroid game implementation has already be solved. So I think this one can be marked as closed. Other remaining tasks can be separated!
