### ISSUE TITLE
4-Column to 3-Column Layout: Category Page Listings

### ISSUE THREAD

**Issue by josephcotten** [tomswain84/daskeyboardsite#49]
The client has requested that we edit the design of the Keyboards category page to use a **3-column layout @ large viewport sizes**. Currently we use 3-column for medium-size screens (Tablet size or small computer display size), but it goes to 4-column at large widths. We want to stay at 3-column for large screen sizes.

I created a quick mockup of how this should look and am attaching it here. Please implement this change before launch, if at all possible. Let me know if you need any more clarification on this.

Pages affected:
https://dascommerce.vercel.app/category/mechanical-keyboards
We are **not** changing the Accessories category template. Only the Keyboards category listing.

Thanks!
![3-col](https://user-images.githubusercontent.com/9754619/184355873-a4cd8eee-8b10-448c-bc61-7a7648db8b9d.jpg)

**Comment by mrth2** [comment]
@josephcotten  the keyboard category page layout is fixed
