### ISSUE TITLE
Create New MacTigr Page (Didn’t Exist Previously)

### ISSUE THREAD

**Issue by josephcotten** [tomswain84/daskeyboardsite#50]
Das Keyboard’s new product just launched! This is exciting, and we’ll need to port over their new product page to our NextJS website. The DK team spent a lot of time on the design of their new landing page for MacTigr, making it match the look of Apple products in many ways.

**Design:** we want to use their design ( https://www.daskeyboard.com/mactigr/ ) on our new website, with the exception of fonts. We will use our site‘s fonts, but we should honor the layout, copy, graphics, and overall design of the MacTigr page on daskeyboard.com when we build it on NextJS.

This has to be done before launch, since the MacTigr keyboard has been released already to the public. We will of course need to make sure the URL after launch remains https://www.daskeyboard.com/mactigr/ as well.

**Comment by josephcotten** [comment]
We’ll also need to create a category listing tile for it, to appear on this page:https://dascommerce.vercel.app/category/mechanical-keyboards?filter=formac

And of course a commerce page with the product details, such as we have on other products (https://dascommerce.vercel.app/commerce/4-professional-for-mac ). Additional photos and all Shopify data available at https://shop.daskeyboard.com/collections/all-mechanical-keyboards/products/das-keyboard-mactigr?variant=40127599902803

**Comment by daviddubrino** [comment]
Here is the embed code for the YouTube, as well as all of the assets so you don't have to try to find them:

- [Main site Images](https://drive.google.com/drive/folders/1NkUZYHRqdMfnBmL--CH_dScNnYPKmzAg?usp=sharing)
- [Shopify/Commerce Page](https://drive.google.com/drive/folders/1OT1t5eOGsATu3GqMVgwpWGHmsGFhE3Aq?usp=sharing) (but these might pull automatically?)

- YouTube Embed code: 
```<iframe width="560" height="315" src="https://www.youtube.com/embed/ohW2FXjhR_8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>```

**Comment by daviddubrino** [comment]
Here's the master folder will all the design files as well: https://drive.google.com/drive/folders/1hUnLzRR19UwumL1bsXsZrm9B5BbBLTf0?usp=sharing

**Comment by josephcotten** [comment]
@mrth2 does this give you everything you need to build the product/commerce page for MacTigr?

**Comment by daviddubrino** [comment]
Here's the existing page as well @mrth2 : https://www.daskeyboard.com/mactigr/

**Comment by mrth2** [comment]
yes @josephcotten

**Comment by mrth2** [comment]
@daviddubrino  I lost my access to www.daskeyboard.com repository. Can you grant me again?

**Comment by mrth2** [comment]
@daviddubrino  @josephcotten Here is the new mactigr product: https://dascommerce.vercel.app/mactigr

**Comment by daviddubrino** [comment]
> 

Do you have access now? I don't have access but @supercobra can add you if needed

**Comment by mrth2** [comment]
@daviddubrino  I don't have access now

**Comment by daviddubrino** [comment]
@supercobra can you add @mrth2 back to the www.daskeyboard.com repository?

**Comment by josephcotten** [comment]
@mrth2 did you regain access to the daskeyboard.com repository?

**Comment by mrth2** [comment]
@josephcotten  still not. I copied texts from the live site so right now don't really need the access. For further updates I may need so it's better if I can have the access until we fully launch

**Comment by josephcotten** [comment]
@supercobra we lost access to the daskeyboard.com Git repository. Can you (or someone on your team) grant access to @mrth2 ?
