### ISSUE TITLE
Q Applet Design, JSON, template file port into NextJS

### ISSUE THREAD

**Issue by josephcotten** [tomswain84/daskeyboardsite#51]
I’m adding an Issue ticket here to make sure we have a place to comment on the Q Applets Pages project.

Here’s a link to the Miro board with information: https://miro.com/app/board/uXjVOX2cK9w=/?moveToWidget=3458764531177212929&cot=14

**Comment by mrth2** [comment]
@josephcotten  https://dascommerce.vercel.app/technology/q-software/applet?name=ram-usage
