### ISSUE TITLE
Image not centered on product page

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#53]
On the Prime 13 page this image isn't centered: https://dascommerce.vercel.app/prime-13

![dk6-block3](https://user-images.githubusercontent.com/14006273/186232646-af1a4a6c-b10e-4641-96a8-dae7a9d99ca3.png)

**Comment by mrth2** [comment]
@daviddubrino  image is not centered https://dascommerce.vercel.app/prime-13
