### ISSUE TITLE
Remove "Win a free keyboard" on all pages but the homepage

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#54]
Hopefully, this isn't a manual process, but if it is, then let me know and we may want to backlog it:

![image](https://user-images.githubusercontent.com/14006273/186234919-a3d91321-c0bf-4070-b3a5-14740ecbb353.png)

**Comment by mrth2** [comment]
@daviddubrino  the giveaway CTA is now only showing on home page:
https://dascommerce.vercel.app/4-professional 
https://dascommerce.vercel.app/
