### ISSUE TITLE
Spacing issue on DK4 pro page

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#55]
I'm pretty sure this spacing is off on this page: https://dascommerce.vercel.app/4-professional

![image](https://user-images.githubusercontent.com/14006273/186251954-e0735d39-fd44-4102-a3b5-56f600427db7.png)

**Comment by mrth2** [comment]
@daviddubrino spacing fixed  https://dascommerce.vercel.app/4-professional
