### ISSUE TITLE
Category pages keyboard card alignment is off

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#56]
This was discussed a number of times before, but we need to have all the keyboard cards be the same size on the category pages so that they are aligned. The solution was to have them all be the largest possible height with the different tags and text that could be present: https://dascommerce.vercel.app/category/mechanical-keyboards?filter=all

This includes filter pages like this: https://dascommerce.vercel.app/category/mechanical-keyboards?filter=formac

![image](https://user-images.githubusercontent.com/14006273/186680673-191b3b26-762a-4741-b36e-ec33c96d35b6.png)

**Comment by mrth2** [comment]
@daviddubrino  cards height have been aligned
