### ISSUE TITLE
Meta title is displaying Das&;nbsp;Keyboard story on history page

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#58]
On this page the meta title is displaying the HTML: https://dascommerce.vercel.app/history

<img width="331" alt="Screen Shot 2022-08-25 at 8 00 14 AM" src="https://user-images.githubusercontent.com/14006273/186700161-006b6b90-025d-40b5-bafa-6d38b238c8c0.png">
<img width="97" alt="Screen Shot 2022-08-25 at 8 00 07 AM" src="https://user-images.githubusercontent.com/14006273/186700165-154cdb26-daef-4163-af4f-cf50821b5387.png">

**Comment by mrth2** [comment]
@daviddubrino meta title updated
