### ISSUE TITLE
Have press release links open in new tab

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#59]
We should really open these in a new tab, instead of having them leave the site: https://dascommerce.vercel.app/company-information/press-kit

**Comment by mrth2** [comment]
@daviddubrino  press kit link target updated

**Comment by daviddubrino** [comment]
I'm not seeing these open in a new window? Should be `target="_blank"`

It might not be deployed so feel free to reclose if it is pushed..

**Comment by daviddubrino** [comment]
Ah, I see, it's the press releases: 

![image](https://user-images.githubusercontent.com/14006273/187292062-df915f4f-26fd-498a-a25d-bf527476874e.png)

**Comment by mrth2** [comment]
@daviddubrino link updated
