### ISSUE TITLE
Organization & Navigation Tweaks & Fixes

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#6]
Here is a list of tweaks to the organization and navigation of the site, and static pages missing. I will create a new git issue with URL structure changes as well. 

### Top Nav and Product Category Pages

- [x] Keyboards top Nav: Move Best Sellers to the top of the top nav:
![image](https://user-images.githubusercontent.com/14006273/173103722-fa19de00-1634-47a5-a539-8e75955e3fac.png)

- [x] Keyboards Top Nav: The Best Sellers filter doesn't work
Vercel: https://dascommerce.vercel.app/products/category-mechanical-keyboards?filter=bestsellers
What it should be: https://shop.daskeyboard.com/collections/best-sellers

- [x] Keyboard All page's Linux filter doesn't show any products:
Vercel: https://dascommerce.vercel.app/products/category-mechanical-keyboards?filter=linux
Should be (without the warranty): https://shop.daskeyboard.com/collections/linux-keyboards

- [x] Keyboards Top Nav: No page for Refurbished
Can duplicate all product pages, with the below text at the top of the category page, and each product page, highlighted in some way: https://shop.daskeyboard.com/collections/refurbished-mechanical-keyboards
**_All Certified Refurbished orders are non-refundable. Certified Refurbished products are pre-owned, certified to be free of defects, and come with a 30-day limited hardware warranty. If the product is defective or does not work, a replacement will be sent. Please refer to our guarantee page at [www.daskeyboard.com/guarantee](http://www.daskeyboard.com/guarantee)_**
![image](https://user-images.githubusercontent.com/14006273/173106030-45e8aa2d-a5a1-496c-90a2-71a744c1cb67.png)
![image](https://user-images.githubusercontent.com/14006273/173106095-d302d8d4-afb4-4d6c-8c6c-72859a127cef.png)

- [x] Accessories top Nav Drop Down re-order: 
Keycap Sets
Palm Rests
Keyboard Parts
---Remove--- Mouse Pads
Das Swag
Warehouse Clearance
+ All Accessories

### Static Pages that Don't Exist: 
- [x] Technology/Q Software: https://dascommerce.vercel.app/technology/q-software, should be: https://www.daskeyboard.com/technology/q-software/
   - You can use [this theme](https://dascommerce.vercel.app/products/daskeyboard-x50q), remove the buy button, then this is a white BG image to replace the black version on the existing site: 
![5Q-Applet-Dashboard-Developer-Keyboard-White-2700x1500](https://user-images.githubusercontent.com/14006273/173386235-9a767a20-260b-48d2-b341-6f2deedd29c0.png)

   
- [x] Technology/Gamma Zulu:  https://dascommerce.vercel.app/technology/gamma-zulu-switch Should be: https://www.daskeyboard.com/technology/gamma-zulu-switch/
   - You can use [this theme](https://dascommerce.vercel.app/products/daskeyboard-x50q), I don't have a white image for this so let me know if that's a problem. 
   
- [x] Footer: Professional Reviews: https://dascommerce.vercel.app/reviews, should be: https://www.daskeyboard.com/reviews/
  - I guess we can use this page as the theme for now, but we may need a new design for this page: https://www.4eighty.com/sites/daskeyboard/privacy-policy.php
  
- [x] Footer: Mechanical Keyboard Blog Post: https://dascommerce.vercel.app/mechanical-keyboard-guide, should just link to: https://www.daskeyboard.com/blog/mechanical-keyboard-guide/

- [x] 5 Meta Hacks (not linked to on site FYI): https://www.daskeyboard.com/5-meta-hacks/
  - You can just use the basic static page theme: https://www.4eighty.com/sites/daskeyboard/company-information/become-a-reseller.php 
- [x] Impressum: https://www.daskeyboard.com/imprint/
  - You can just use the basic static page theme: https://www.4eighty.com/sites/daskeyboard/company-information/become-a-reseller.php 
- [x] Type Faster Page: https://dascommerce.vercel.app/typefaster should be: https://www.daskeyboard.com/typefaster/
  - Maybe you can use this static page theme: https://www.4eighty.com/sites/daskeyboard/history.php
- [x] Compare Keyboards: https://dascommerce.vercel.app/compare-keyboards should be: https://www.daskeyboard.com/compare-keyboards/ - I believe you have the code for this already. 
  - You can just use the basic static page theme: https://www.4eighty.com/sites/daskeyboard/company-information/become-a-reseller.php 

### Minor Tweaks:
- [x] On the privacy policy page there's some vertical spacing issue with the first bullet list because it goes onto a second line: https://dascommerce.vercel.app/privacy-policy
![image](https://user-images.githubusercontent.com/14006273/173106901-a641bd0c-a0a5-4c01-aeea-41dac7455d8d.png)

- [x] The Shop By Category button doesn't look vertically aligned correctly, the way the other little buttons were that Joseph fixed in the CSS: https://dascommerce.vercel.app/products/category-mechanical-keyboards?filter=all
![image](https://user-images.githubusercontent.com/14006273/173392508-74b15c2d-06d5-401c-9b59-aab4a1c550db.png)

**Comment by mrth2** [comment]
@josephcotten @daviddubrino  all tasks here are done and deployed successfully! 
- refurbished: https://dascommerce.vercel.app/products/category/refurbished-mechanical-keyboards
