### ISSUE TITLE
Site updates for MacTigr

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#60]
There are a number of other places that will need to be updated for the MacTigr, the /history page, the press page, the category page and filters, and the homepage. 

These will need to be updated prior to launch: 

- [x] Add Mactigr with English and German translations for the [press release, and media kit downloads](https://dascommerce.vercel.app/company-information/press-kit) here, [updated press release link, and images here](https://www.daskeyboard.com/company-information/press-kit/)
- [x] The [history page's main text is updated on the existing site](https://dascommerce.vercel.app/history), as well as the addition of the MacTigr. The same text and images will need to be [added to the Vercel site](https://dascommerce.vercel.app/history) 
  - Introduction text: How did it start?
Austin, Texas, 2005. It all started from a personal quest to improve his own typing speed and accuracy. Metadot founder and “Uber Geek” Daniel Guermeur (Twitter: @supercobra) created a blank keyboard. His typing speed doubled after just a few weeks of use. Friends, colleagues, and intrigued tech users who tested the keyboard were mesmerized, and wanted one. Das Keyboard was born.
  - MacTigr text: Das Keyboard Introduces the MacTigr, a Low-Profile Mechanical Keyboard for Macs
In August 2022, Das Keyboard launches the MacTigr, low-profile mechanical keyboard designed for the Mac. Made with an unibody aluminum enclosure, MacTigr uses Cherry MX low-profile linear switches, low-profile double-shot PBT keycaps, and a 2-port USB-C hub. The MacTigr also features a dedicated volume knob, media controls, and a dedicated sleep button.
  - [And image](https://www.daskeyboard.com/images/press-kit/thumbnails/mactigr/right.jpg) 
  
- [x] Once the MacTigr is added to the site it will need to be added to the categories. It will be the first product on the list with the NEW flag.

  - Text & [image](https://drive.google.com/file/d/15-5nk-RNKswKQJX-veJhSb6QAR8fCF7e/view?usp=sharing): 
Das Keyboard MacTigr 
Starting at $219 
Supercharged  Minimalist  Aluminum  
Mac Made for Mac. 100% metal unibody construction. Low-profile enclosure, low-profile keycaps.

**Comment by mrth2** [comment]
@daviddubrino all three tasks have been solved
