### ISSUE TITLE
Adding MacTigr to compare pare criteria

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#61]
We will need to add the compare page to the "Choose keyboards" feature on the website: https://www.daskeyboard.com/compare-keyboards/

Here is the criteria for the MacTigr:

- Category: Professional			
- Switch type: Mechanical			
- Switches brand: Cherry MX Low-Profile			
- Q smart button: No checkmark			
- LED backlighting: No checkmark			
- Keyboard size: Ful size			
- Built-in USB hub: 2 port, Usb3.1 gen1 5Gbps			
- Media controls: Dedicated media controls			
- Aluminum top panel: Stainless Steel Top Panel			
- Wrist rest: No checkmark			
- Key detection			
- NKRO: Checkmark			
- Cable type: ABS			
- Switch lifecycle: 100 million			
- Contact type: Gold plated single cross-point			
- Volume knob: Checkmark			
- Keycap type: Low-profile double shot PBT			
- Feet type: Non-slip footpads			
- Windows key disable control: N/A			
- Cable length: 6 ft (1.83 m)		
- Mac OS specific key functions: Checkmark			
- OS compatibility: macOS			
- Dimensions WxHxD: 17.16 x 5.0 x 1.06 inches (43.6 x 12.7 x 2.7 cm)			
- Weight: 2.43 lbs (1.10 kg) 			
- Interchangeable top panels: No checkmark			
- Price: $219

**Comment by daviddubrino** [comment]
This is already on the existing production site, so not sure if you share the same file @mrth2

**Comment by mrth2** [comment]
@daviddubrino  mactigr has been added to compare page
