### ISSUE TITLE
Video autoplays when you visit a page on mobile

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#63]
When you visit any of these pages, the video pops up and auto plays which is not the desired behavior: https://dascommerce.vercel.app/5qs
https://dascommerce.vercel.app/refurbished-5qs
https://dascommerce.vercel.app/x50q
https://dascommerce.vercel.app/refurbished-x50q
https://dascommerce.vercel.app/4q
https://dascommerce.vercel.app/refurbished-4q

![IMG_82880C63E15E-1](https://user-images.githubusercontent.com/14006273/187211035-dea4012d-de9d-456b-89b7-1b81c05eb6af.jpeg)

**Comment by mrth2** [comment]
@daviddubrino do you mean the youtube video section is auto playing on the mobile? It does not happen to me like that. May be it's your device settings

**Comment by daviddubrino** [comment]
No, it's not the youtube video, its the video pictured above that on an iPhone starts automatically in full screen as pictured: https://dascommerce.vercel.app/video/q-applet.mp4

**Comment by josephcotten** [comment]
Here’s a screencast from my phone showing this behavior: 

https://user-images.githubusercontent.com/9754619/187527886-c78279d3-75db-4257-89c4-9b1fa1dacc3d.mp4

**Comment by josephcotten** [comment]
And a little add-on recap: https://www.loom.com/share/89771a33743a455fa853d48908dec169

**Comment by mrth2** [comment]
@josephcotten  @daviddubrino  please try again. I added a fix to this one then it should work ( I don't use iphone  & it doesnot happen on android )

**Comment by daviddubrino** [comment]
It is not occurring now, and the video no longer autoplay but will wait for @josephcotten to also confirm.

**Comment by josephcotten** [comment]
David’s right. The video is no longer going full-screen ( great job, @mrth2 !) however, the video is duplicated on the page. Can you do a CSS quick fix of display:none; at small media width?

**Comment by mrth2** [comment]
@josephcotten @daviddubrino  yeah thanks for pointing it out. Now it's fixed.
