### ISSUE TITLE
404 Page with suggested product for Model S for Mac on the 4 Pro for Mac commerce page

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#64]
There is a 404 link on the Model S for Mac suggested product here: https://dascommerce.vercel.app/commerce/4-professional-for-mac

404 link: https://dascommerce.vercel.app/products/commerce/model-s-pro-for-mac, on the actual product page it's https://dascommerce.vercel.app/commerce/model-s-pro-for-mac

![bad-link](https://user-images.githubusercontent.com/14006273/187211694-ef6309cd-39a6-4cb8-97c9-4a21ba7ab7df.png)

**Comment by mrth2** [comment]
@daviddubrino  links fixed
