### ISSUE TITLE
Press releases on DE press page not in German

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#66]
On the Vercel site there are some translations missing: https://dascommerce.vercel.app/de/company-information/press-kit  

They can be found here: https://www.daskeyboard.com/de/company-information/press-kit/

![image](https://user-images.githubusercontent.com/14006273/187264118-6622a1a0-d269-4b88-8ce3-c5912ca214b9.png)

**Comment by mrth2** [comment]
@daviddubrino I understood it wrong. Now fixed
