### ISSUE TITLE
History page MacTigr image broken & typo

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#67]
On this page the MacTigr image is missing at the bottom : https://dascommerce.vercel.app/history

The I is also missing from the beginning of the sentence in German for the MacTigr: https://dascommerce.vercel.app/de/history
![image](https://user-images.githubusercontent.com/14006273/187265028-450afdab-36fd-4c3b-a2e5-a85b26da9048.png)

**Comment by mrth2** [comment]
@daviddubrino  content updated
