### ISSUE TITLE
MacTigr product page edits

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#68]
Here are a few items that aren't the same on the Vercel site: https://dascommerce.vercel.app/mactigr

- [x] The text should overlap the hero image the way it does on the main site for the hero image:
Vercel https://dascommerce.vercel.app/mactigr 
![image](https://user-images.githubusercontent.com/14006273/187299384-a03c1e4c-402b-4706-9a8c-1782225eab6b.png)

Vs. existing site: https://www.daskeyboard.com/mactigr/
![image](https://user-images.githubusercontent.com/14006273/187241716-5465f426-dff9-4ce2-9fb1-e234ab486a27.png)

- [x] The font and bolding aren't the same as on the existing site, and we'd like them to be on this page because it looks better:
Vercel site: 
![image](https://user-images.githubusercontent.com/14006273/187297914-586b3318-2b22-49f4-a45c-42d292029cea.png)

Existing site:

![image](https://user-images.githubusercontent.com/14006273/187297971-13c7db3f-ad82-439c-9477-2a30bc6e0697.png)

- [ ] The capitalization should also be the same as on the existing site:
   - [x] The hero headline shouldn't be capitalized and should be like this: The real king of the jungle.
   - [x] Below `100% Metal`, it should be lowercase (besides Mac): A reference mechanical keyboard for Mac users.
   - [x] All of the feature headlines should only have the first word capitalized (sentence case): 100% metal, Mac features, USB-C hub, Cherry MX red switches, Low profile keycaps
   - [x] Only the first word should be capitalized in this headline: Turbo-charge your workspace.
   - [x] Same here, only the first word should be capitalized: Energy-saving sleep button. Save energy, save the planet.
   - [x] Switches shouldn't be capitalized on this headline: German-engineered Cherry MX switches. And same for this title above the bullets: Low-profile Cherry MX red switch
   - [x] Only the first word should be capitalized: When typing becomes an experience.

**Comment by mrth2** [comment]
@daviddubrino  the font was suggested by @josephcotten  to use same as on NextJs version. Do you still want to use the font from live site instead?

**Comment by mrth2** [comment]
@daviddubrino all issues are resolved, including font
