### ISSUE TITLE
Refurbished category page not showing correct prices

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#69]
The refurbished category isn't showing the correct prices, and show a 0% discount: https://dascommerce.vercel.app/category/refurbished-mechanical-keyboards

![image](https://user-images.githubusercontent.com/14006273/188241504-8f428390-2b6b-43ce-b2b3-9cb4f5dce450.png)

**Comment by mrth2** [comment]
@daviddubrino refurbished prices updated
