### ISSUE TITLE
Remove Wishlist Links/Buttons

### ISSUE THREAD

**Issue by josephcotten** [tomswain84/daskeyboardsite#71]
As we wait for NextJS Commerce to finish the Wishlist API, we should remove or hide the wishlist links and buttons on our Vercel website. Please remove it from the header nav menu, and let’s do a display:none or visibility:hidden for all the product pages’ “Add to Wishlist” buttons.

**Comment by mrth2** [comment]
@josephcotten  wishlist options are hidden
