### ISSUE TITLE
Found a UX issue with navigation

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#8]
After using the site a lot more I've realized once you start scrolling on a product page, there's no way to navigate anywhere and you're stuck on the page unless you scroll to the top. Looking for ideas on how to handle this gracefully? 
![image](https://user-images.githubusercontent.com/14006273/174293943-97097d6d-333a-4a3a-a2f2-bf0b40aa5f77.png)

**Comment by josephcotten** [comment]
@daviddubrino Tom isn’t working on this project any more. We’ll need to track these design changes and wrap them into a final design push after the Next.js and Shopify development is finished.

**Comment by josephcotten** [comment]
@daviddubrino the most common thing here is some sort of “back to top” link, either at the bottom of each page, or perhaps as a hovering upward-pointing arrow which appears at the lower right of the screen when the user scrolls past the mid-way point of the page, such as is seen here: https://elfsight.com/back-to-top-widget/examples/

Would you like us to roll this into the design tweaks?

**Comment by daviddubrino** [comment]
Great, idea, here's an example of the design of the one we like if we could use this with the same gray, then our red accent color as the arrow: https://www.pulsar.gg/products/low-profile-keycaps-kr
![image](https://user-images.githubusercontent.com/14006273/175966497-fdc0e3e0-7ab7-4382-bacb-e35a7db2b009.png)

**Comment by josephcotten** [comment]
@mrth2 is there a quick/easy way in NextJS to add a scroll-to-top button on the website? Something like the example above?

**Comment by mrth2** [comment]
@josephcotten  added this 
<img width="141" alt="image" src="https://user-images.githubusercontent.com/8658653/176337278-efa42e3c-cb20-4f44-88f8-11ef234d10a3.png">
