### ISSUE TITLE
Design site down? 

### ISSUE THREAD

**Issue by daviddubrino** [tomswain84/daskeyboardsite#9]
Is anyone seeing the 4eighty site down? 

https://www.4eighty.com/sites/daskeyboard/index.php

![image](https://user-images.githubusercontent.com/14006273/174308610-ae1d6874-3e05-4b16-8ad2-aba988e422fb.png)

**Comment by josephcotten** [comment]
I’m seeing that as well. Looks like the SSL certificate expired on that staging domain. I’m looking into it now.
@mrth2 is it possible to quickly go into the php files (or maybe it’s an .htaccess thing) and remove the forced http**s** redirect? If we can force the php site to load in http, we should be able to keep working from it.

**Comment by josephcotten** [comment]
Just documenting the workaround for this: if you’re using a Chromium browser (Brave, Chrome, etc), click inside the error page and type on your keyboard, “thisisunsafe” (without quotation marks), and you’ll be able to enter the site.
